package com.jobportal.utility;

public class Data {
    public static String getMessageBody(String otp,String username) {
        return    "<!DOCTYPE html>"
                + "<html lang='en'>"
                + "<head>"
                + "    <meta charset='UTF-8'>"
                + "    <meta name='viewport' content='width=device-width, initial-scale=1.0'>"
                + "    <title>OTP Email</title>"
                + "    <style>"
                + "        body {"
                + "            font-family: Arial, sans-serif;"
                + "            margin: 0;"
                + "            padding: 0;"
                + "            background-color: #f7f7f7;"
                + "        }"
                + "        .email-container {"
                + "            max-width: 600px;"
                + "            margin: 20px auto;"
                + "            background-color: #ffffff;"
                + "            padding: 20px;"
                + "            border-radius: 8px;"
                + "            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);"
                + "        }"
                + "        .header {"
                + "            text-align: center;"
                + "            padding-bottom: 20px;"
                + "            border-bottom: 1px solid #dddddd;"
                + "        }"
                + "        .header h1 {"
                + "            font-size: 24px;"
                + "            color: #333333;"
                + "            margin: 0;"
                + "        }"
                + "        .content {"
                + "            margin: 20px 0;"
                + "            font-size: 16px;"
                + "            color: #555555;"
                + "            line-height: 1.6;"
                + "        }"
                + "        .otp {"
                + "            display: block;"
                + "            font-size: 20px;"
                + "            color: #ffffff;"
                + "            background-color: #4CAF50;"
                + "            padding: 10px;"
                + "            text-align: center;"
                + "            border-radius: 5px;"
                + "            margin: 20px auto;"
                + "            width: fit-content;"
                + "        }"
                + "        .footer {"
                + "            text-align: center;"
                + "            margin-top: 20px;"
                + "            font-size: 12px;"
                + "            color: #aaaaaa;"
                + "        }"
                + "    </style>"
                + "</head>"
                + "<body>"
                + "    <div class='email-container'>"
                + "        <div class='header'>"
                + "            <h1>Your OTP Code</h1>"
                + "        </div>"
                + "        <div class='content'>"
                + "            <p>Hello <strong>" + username + "</strong>,</p>"
                + "            <p>We received a request to verify your account. Use the OTP below to complete the process:</p>"
                + "            <p class='otp'>" + otp + "</p>"
                + "            <p>The OTP is valid for 10 minutes. If you did not request this, please ignore this email.</p>"
                + "        </div>"
                + "        <div class='footer'>"
                + "            <p>Thank you for using our service.</p>"
                + "            <p>&copy; 2024 Your Company Name</p>"
                + "        </div>"
                + "    </div>"
                + "</body>"
                + "</html>";
    }
}

